<?php echo $this->renderTabs($this->tabs); ?>
<h3>Prerequisites</h3>
<ul>
	<li>Existing <a href="https://github.com/halonsecurity/sp-enduser">sp-enduser</a> web application</li>
	<li>Enabled <a href="https://github.com/halonsecurity/sp-enduser/blob/master/session-transfer.php.txt">session transfer</a> support in <a href="https://github.com/halonsecurity/sp-enduser">sp-enduser</a> web application</li></li>
</ul>
<h3>Support</h3>
<p>If you need any technical support for this extension just send us an email at <a href="mailto:support@halon.io?Subject=Need support for sp-enduser-plesk extension">support@halon.io</a>.</p>
